### ISSUE TITLE
WINDOW IS TOO BIG

### ISSUE THREAD

**Issue by LIVE4MINT** [FTBTeam/FTB-App-Feedback#102] opened 2021-12-02 19:23 UTC
### What Operating System

MacOS (Latest)

### App Version

I can't see buck its off screen

### UI Version

I can't see buck its off screen too

### Debug Code

its opens as text

### Describe the bug

window too big

### Steps to reproduce

open app, click install modpack and when it restart its gets too big for 13 inch screen(and I can't change size)

### Expected behaviour

idk what I need to say there

### Screenshots

<img width="1280" alt="Снимок экрана 2021-12-02 в 9 16 56 PM" src="https://user-images.githubusercontent.com/95442341/144489057-b604c8ce-b4fb-49fb-8f18-08d496231fde.png">

**Comment by LIVE4MINT** [comment] 2021-12-02 19:24
> Hay, thanks for the issue! Unfortunately it looks like you've not provided a `Debug code`... We require this as it helps us find your issue as quickly as possible.
> 
> ## Please do the following
> Please use the link below to download and run the FTB Debug tool. This is a tool built by our App Developers and will provide you a code that you need to attach to this issue. Please either edit your original issue or add a comment with this code.
> 
> [Windows](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe) // [MacOS](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos) // [Linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)

debug tool opens as text

**Comment by MichaelHillcox** [comment] 2021-12-02 19:30
What size is your screen?

**Comment by 0az** [comment] 2021-12-03 21:32
I can reproduce this bug, which is only an issue because resizing the window doesn't work.

<details>
<summary>Images</summary>
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/30874884/144675187-bb15d35b-911d-4036-9709-fd1dd7228274.png">
<img width="698" alt="image" src="https://user-images.githubusercontent.com/30874884/144675169-8fe12bc6-b3ac-49fe-9230-67708309c5d2.png">
</details>

**Comment by LocoCubano** [comment] 2021-12-04 06:35
This is technically an issue in the windows version as well. You can make the FTB App window larger but you can't get it to scale down much. Below is as small as I can make the window, resolution 1920x1080

![image](https://user-images.githubusercontent.com/25106883/144700282-c1562314-b5e9-40a3-8ee4-340f3a93b7a8.png)

**Comment by LIVE4MINT** [comment] 2021-12-04 08:14
> What size is your screen?

2560x1600

**Comment by MichaelHillcox** [comment] 2021-12-04 14:03
I've made changes to this in dev, our right sidebar is stuck at that width due to ad requirements so I've made some modifications to allow for a slimmer design. I'll keep improving this but I've taken about 300px off of the min width meaning the app can go a lot smaller and once the design has been modified to support it, I'll drop that down even more to allow the footprint to be really small.

**Comment by MichaelHillcox** [comment] 2022-02-11 14:53
A staggered release has been sent off today and this should be fixed soon :+1:

**Closed by MichaelHillcox** 2022-02-11 14:53 UTC
Labels: bug, bug:ui, effect:all, frontend, fix:dev
